#!/usr/bin/env bash

set -euo pipefail

cmd_logout="Log out"
cmd_restart="Restart"
cmd_shutdown="Kill"

program="rw-power"

menu_items="$cmd_logout\n$cmd_restart\n$cmd_shutdown"
cmd=$(echo -e "$menu_items" | rofi -dmenu -i -p "selection (esc to exit):")

case "$cmd" in
    "$cmd_logout")
        loginctl terminate-user "$USER"
        ;;
    "$cmd_restart")
        systemctl reboot
        ;;
    "$cmd_shutdown")
        systemctl poweroff
        ;;
    *)
        echo "$program: invalid option: $cmd"
        ;;
esac
