#!/usr/bin/env bash

set -euo pipefail

program="rw-power"

menu_items="Log out\nRestart\nKill"
cmd=$(echo -e "$menu_items" | rofi -dmenu -i -p "selection:")

case "$cmd" in
    "Log out")
        loginctl terminate-user "$USER"
        ;;
    "Restart")
        systemctl reboot
        ;;
    "Kill")
        systemctl poweroff
        ;;
    *)
        echo "$program: invalid option: $cmd"
        ;;
esac
